// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: holdings.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHolding = `-- name: CreateHolding :one
INSERT INTO holdings (asset_type, name, quantity, buy_price, current_value, buy_date, notes, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, asset_type, name, quantity, buy_price, current_value,
          buy_date, notes, metadata, created_at, updated_at
`

type CreateHoldingParams struct {
	AssetType    string          `json:"asset_type"`
	Name         string          `json:"name"`
	Quantity     pgtype.Numeric  `json:"quantity"`
	BuyPrice     pgtype.Numeric  `json:"buy_price"`
	CurrentValue pgtype.Numeric  `json:"current_value"`
	BuyDate      pgtype.Date     `json:"buy_date"`
	Notes        string          `json:"notes"`
	Metadata     json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateHolding(ctx context.Context, arg CreateHoldingParams) (Holding, error) {
	row := q.db.QueryRow(ctx, createHolding,
		arg.AssetType,
		arg.Name,
		arg.Quantity,
		arg.BuyPrice,
		arg.CurrentValue,
		arg.BuyDate,
		arg.Notes,
		arg.Metadata,
	)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.AssetType,
		&i.Name,
		&i.Quantity,
		&i.BuyPrice,
		&i.CurrentValue,
		&i.BuyDate,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHolding = `-- name: DeleteHolding :execrows
DELETE FROM holdings WHERE id = $1
`

func (q *Queries) DeleteHolding(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHolding, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listHoldings = `-- name: ListHoldings :many
SELECT id, asset_type, name, quantity, buy_price, current_value,
       buy_date, notes, metadata, created_at, updated_at
FROM holdings
ORDER BY asset_type, created_at DESC
`

func (q *Queries) ListHoldings(ctx context.Context) ([]Holding, error) {
	rows, err := q.db.Query(ctx, listHoldings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Holding
	for rows.Next() {
		var i Holding
		if err := rows.Scan(
			&i.ID,
			&i.AssetType,
			&i.Name,
			&i.Quantity,
			&i.BuyPrice,
			&i.CurrentValue,
			&i.BuyDate,
			&i.Notes,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHolding = `-- name: UpdateHolding :one
UPDATE holdings
SET asset_type    = $1,
    name          = $2,
    quantity      = $3,
    buy_price     = $4,
    current_value = $5,
    buy_date      = $6,
    notes         = $7,
    metadata      = $8,
    updated_at    = NOW()
WHERE id = $9
RETURNING id, asset_type, name, quantity, buy_price, current_value,
          buy_date, notes, metadata, created_at, updated_at
`

type UpdateHoldingParams struct {
	AssetType    string          `json:"asset_type"`
	Name         string          `json:"name"`
	Quantity     pgtype.Numeric  `json:"quantity"`
	BuyPrice     pgtype.Numeric  `json:"buy_price"`
	CurrentValue pgtype.Numeric  `json:"current_value"`
	BuyDate      pgtype.Date     `json:"buy_date"`
	Notes        string          `json:"notes"`
	Metadata     json.RawMessage `json:"metadata"`
	ID           int32           `json:"id"`
}

func (q *Queries) UpdateHolding(ctx context.Context, arg UpdateHoldingParams) (Holding, error) {
	row := q.db.QueryRow(ctx, updateHolding,
		arg.AssetType,
		arg.Name,
		arg.Quantity,
		arg.BuyPrice,
		arg.CurrentValue,
		arg.BuyDate,
		arg.Notes,
		arg.Metadata,
		arg.ID,
	)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.AssetType,
		&i.Name,
		&i.Quantity,
		&i.BuyPrice,
		&i.CurrentValue,
		&i.BuyDate,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
