// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Holding struct {
	ID           int32              `json:"id"`
	AssetType    string             `json:"asset_type"`
	Name         string             `json:"name"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	BuyPrice     pgtype.Numeric     `json:"buy_price"`
	CurrentValue pgtype.Numeric     `json:"current_value"`
	BuyDate      pgtype.Date        `json:"buy_date"`
	Notes        string             `json:"notes"`
	Metadata     json.RawMessage    `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
