// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package drdb

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Holding struct {
	ID           int32              `json:"id"`
	AssetType    string             `json:"asset_type"`
	Name         string             `json:"name"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	BuyPrice     pgtype.Numeric     `json:"buy_price"`
	CurrentValue pgtype.Numeric     `json:"current_value"`
	BuyDate      pgtype.Date        `json:"buy_date"`
	Notes        string             `json:"notes"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ShareholdingPatternStore struct {
	Symbol     string             `json:"symbol"`
	QuarterEnd string             `json:"quarter_end"`
	Pattern    json.RawMessage    `json:"pattern"`
	FetchedAt  pgtype.Timestamptz `json:"fetched_at"`
}

type SupplyChainStore struct {
	Symbol     string             `json:"symbol"`
	ReportYear string             `json:"report_year"`
	Entities   json.RawMessage    `json:"entities"`
	Financials []byte             `json:"financials"`
	ParsedAt   pgtype.Timestamptz `json:"parsed_at"`
}
