// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shareholding.sql

package drdb

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestShareholding = `-- name: GetLatestShareholding :one
SELECT pattern, fetched_at FROM shareholding_pattern_store
WHERE symbol = $1
ORDER BY fetched_at DESC
LIMIT 1
`

type GetLatestShareholdingRow struct {
	Pattern   json.RawMessage    `json:"pattern"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) GetLatestShareholding(ctx context.Context, symbol string) (GetLatestShareholdingRow, error) {
	row := q.db.QueryRow(ctx, getLatestShareholding, symbol)
	var i GetLatestShareholdingRow
	err := row.Scan(&i.Pattern, &i.FetchedAt)
	return i, err
}

const upsertShareholding = `-- name: UpsertShareholding :exec
INSERT INTO shareholding_pattern_store (symbol, quarter_end, pattern)
VALUES ($1, $2, $3)
ON CONFLICT (symbol, quarter_end) DO UPDATE
    SET pattern = EXCLUDED.pattern, fetched_at = NOW()
`

type UpsertShareholdingParams struct {
	Symbol     string          `json:"symbol"`
	QuarterEnd string          `json:"quarter_end"`
	Pattern    json.RawMessage `json:"pattern"`
}

func (q *Queries) UpsertShareholding(ctx context.Context, arg UpsertShareholdingParams) error {
	_, err := q.db.Exec(ctx, upsertShareholding, arg.Symbol, arg.QuarterEnd, arg.Pattern)
	return err
}
