// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: supply_chain.sql

package drdb

import (
	"context"
	"encoding/json"
)

const getSupplyChain = `-- name: GetSupplyChain :one
SELECT entities FROM supply_chain_store
WHERE symbol = $1 AND report_year = $2
`

type GetSupplyChainParams struct {
	Symbol     string `json:"symbol"`
	ReportYear string `json:"report_year"`
}

func (q *Queries) GetSupplyChain(ctx context.Context, arg GetSupplyChainParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getSupplyChain, arg.Symbol, arg.ReportYear)
	var entities json.RawMessage
	err := row.Scan(&entities)
	return entities, err
}

const upsertSupplyChain = `-- name: UpsertSupplyChain :exec
INSERT INTO supply_chain_store (symbol, report_year, entities)
VALUES ($1, $2, $3)
ON CONFLICT (symbol, report_year) DO UPDATE
    SET entities = EXCLUDED.entities, parsed_at = NOW()
`

type UpsertSupplyChainParams struct {
	Symbol     string          `json:"symbol"`
	ReportYear string          `json:"report_year"`
	Entities   json.RawMessage `json:"entities"`
}

func (q *Queries) UpsertSupplyChain(ctx context.Context, arg UpsertSupplyChainParams) error {
	_, err := q.db.Exec(ctx, upsertSupplyChain, arg.Symbol, arg.ReportYear, arg.Entities)
	return err
}
