package backtest

import "time"

// OHLCV represents a single day's price data.
type OHLCV struct {
	Date   time.Time
	Open   float64
	High   float64
	Low    float64
	Close  float64
	Volume int64
}

// SignalAction represents a trading action.
type SignalAction string

const (
	Buy  SignalAction = "BUY"
	Sell SignalAction = "SELL"
)

// Signal is a trading signal generated by a strategy for a specific date.
type Signal struct {
	Date   time.Time
	Action SignalAction
	Price  float64
}

// Strategy generates trading signals from historical price data.
// All future strategies — built-in or user-defined — implement this interface.
type Strategy interface {
	Name() string
	GenerateSignals(prices []OHLCV) []Signal
}
